### ISSUE TITLE
mac 下命令python3 manage.py runserver出错

### ISSUE THREAD

**Issue by RunFeifei** [kukyxs/blog_project#1]
django.db.utils.OperationalError: (2003, "Can't connect to MySQL server on 'localhost' ([Errno 61] Connection refused)")

貌似是 python3缺少 mysqldb 请问有遇到这种问题吗?

**Comment by kukyxs** [comment]
检测是否安装了 pymysql 模块，然后在项目下的 __init__.py 初始化，解决不了的话可以加我微信，yu_kuky
